# Generated by Django 4.1.1 on 2022-10-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
