# Generated by Django 4.1.1 on 2022-10-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_players_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='playerId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='playername',
            new_name='name',
        ),
    ]
