# Generated by Django 4.1.1 on 2022-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_playerid_players_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='score',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
